// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRlN-qEsd3rDVCLNeIAf8shOnaMAvQAtM',
    appId: '1:41943056602:web:376460c9cd7e2bf85065e3',
    messagingSenderId: '41943056602',
    projectId: 'e-commerceproject-7e376',
    authDomain: 'e-commerceproject-7e376.firebaseapp.com',
    storageBucket: 'e-commerceproject-7e376.firebasestorage.app',
    measurementId: 'G-YCER58YN9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrO6KIl3uMaSZtSWvA1peoUZjZSD5ePxE',
    appId: '1:41943056602:android:e2d0557fcfb793265065e3',
    messagingSenderId: '41943056602',
    projectId: 'e-commerceproject-7e376',
    storageBucket: 'e-commerceproject-7e376.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvsWCv2m2sAbtfRsswYIaQx_2H1zthCF0',
    appId: '1:41943056602:ios:ad06649e3deed4a55065e3',
    messagingSenderId: '41943056602',
    projectId: 'e-commerceproject-7e376',
    storageBucket: 'e-commerceproject-7e376.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvsWCv2m2sAbtfRsswYIaQx_2H1zthCF0',
    appId: '1:41943056602:ios:ad06649e3deed4a55065e3',
    messagingSenderId: '41943056602',
    projectId: 'e-commerceproject-7e376',
    storageBucket: 'e-commerceproject-7e376.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRlN-qEsd3rDVCLNeIAf8shOnaMAvQAtM',
    appId: '1:41943056602:web:b5525e60879b61865065e3',
    messagingSenderId: '41943056602',
    projectId: 'e-commerceproject-7e376',
    authDomain: 'e-commerceproject-7e376.firebaseapp.com',
    storageBucket: 'e-commerceproject-7e376.firebasestorage.app',
    measurementId: 'G-D9MXJL9B0X',
  );

}